# Header
menu:
  ## If your site is put in a subdirectory, set Home as '/child/'
  Home: /
  Archives: archives
  About: about.html

social:
  email: git.windomz@gmail.com
  twitter:
  weibo:
  github: WindomZ
  googleplus:
  rss: /atom.xml

# Content
fancybox: true # set to true if you want to use it

duoshuo: #duoshuo_shortname
disqus: https-windomz-github-io
google_analytics: UA-101546872-1
google_adsense_page_level_ads: #Google Adsense Page Level Ads Code
